Database Setup - user table + active_pin table
bcgov/bc-emli-pin-mgmt-be pull request #19
Opened 2023-07-26 14:14 UTC by emilymendelson

This is related to the following tasks:

- https://deloittedigital.atlassian.net/browse/BVPS-126
- https://deloittedigital.atlassian.net/browse/BVPS-127

Files Changed:

- local-db/README.md - Instructions on how to run database SQL locally
- local-db/init-pg.sql - Contains SQL scripts for creating user table and active_pin table
- local-db/Dockerfile
- local-db/docker-compose.yml - to build local database

The create table SQL commands will be updated once LTSA data is received.

2023-07-26 14:31 UTC, ceciliahangzhou approved these changes

2023-07-26 14:39 UTC, hannah-macdonald1 requested changes
One minor change. Otherwise this looks good 👍

2023-07-26 14:39 UTC, hannah-macdonald1 commented on local-db/init-pg.sql
> +CREATE TYPE parcel_status_type AS ENUM ('Active', 'Inactive');
Should be A, I to match the source data

2023-07-26 14:57 UTC, emilymendelson commented on local-db/init-pg.sql
> +CREATE TYPE parcel_status_type AS ENUM ('Active', 'Inactive');
Thank you! I'll update this :)

2023-07-26 15:00 UTC, hannah-macdonald1 approved these changes
👍

2023-07-26 20:25 UTC, ceciliahangzhou approved these changes

2023-07-26 20:52 UTC, hannah-macdonald1 requested changes
A few minor comments, but looks good overall.

2023-07-26 20:52 UTC, hannah-macdonald1 commented on local-db/init-pg.sql
> +    pin VARCHAR(8) NOT NULL,
Based on Brett's updated requirements (recording a homeowner but not immediately issuing a PIN) this cannot be a required (NOT NULL) field

2023-07-26 20:52 UTC, hannah-macdonald1 commented on local-db/init-pg.sql
> +    role VARCHAR(12) NOT NULL
This should probably be an ENUM type instead ('Standard','Admin','SuperAdmin')

2023-07-26 20:52 UTC, hannah-macdonald1 commented on local-db/init-pg.sql
> +CREATE TYPE expiration_reason_type AS ENUM ('OP', 'CC', 'OR', 'CO', 'OT');
Maybe add a comment below the type as to what the reason codes mean so we don't forget? :)

2023-07-26 20:52 UTC, hannah-macdonald1 commented on local-db/init-pg.sql
> +
This one is very likely to change once we know more about the keycloak api output, but better to have it here than not.

2023-07-26 21:03 UTC, emilymendelson commented
> A few minor comments, but looks good overall.

Thank you for going through @hannah-macdonald1! Updated :)

2023-07-26 21:09 UTC, hannah-macdonald1 approved these changes
👍

2023-07-28 15:05 UTC, emilymendelson commented on local-db/init-pg.sql
> +CREATE TYPE parcel_status_type AS ENUM ('A', 'I');
Add definitions for types

2023-07-28 15:07 UTC, emilymendelson commented on local-db/init-pg.sql
> +    -- OT - other
confirm if other is still required

2023-07-28 15:08 UTC, emilymendelson commented on local-db/init-pg.sql
> +CREATE TABLE IF NOT EXISTS "log" (
Change table name to be more descriptive (i.e., pin_audit_log)

2023-07-28 15:08 UTC, emilymendelson commented on local-db/init-pg.sql
> +    token_id UUID PRIMARY KEY NOT NULL,
Drop this table for now

2023-07-28 15:10 UTC, emilymendelson commented on local-db/init-pg.sql
> +CREATE TABLE IF NOT EXISTS "user" (
@ceciliahangzhou go through new requirements and update user table

2023-07-28 15:20 UTC, emilymendelson commented on local-db/init-pg.sql
> +CREATE TABLE IF NOT EXISTS "log" (
done

2023-07-31 14:23 UTC, ceciliahangzhou commented on local-db/init-pg.sql
> +    expired_at DATE,
Updated

2023-07-31 18:45 UTC, hannah-macdonald1 approved these changes
:+1:

2023-07-31 19:04 UTC, habibaz approved these changes

2023-07-31 19:25 UTC, merged